[package]
name = "rusted-commits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rusted-commits"
path = "src/main.rs"

[lib]
name = "git"
path = "src/lib.rs"

[dependencies]
colored = "2.0.0"